#+TITLE: Game Theory 2017
#+AUTHOR: Christoph Schottmüller

* Exam
The exam is planned for January 22nd-25th. Some administrative information:
- preparation is closed book (no notes, books, electronic equipment etc.)
- if you are not there when your name is called, you unfortunately fail
- no electronic equipment (mobile phones, tablets, smart watches etc.) is allowed during preparation or examination; secure storage possibilities for such items  are /not/ provided.

For the exam you should expect the following:
- you randomly draw a question
- you have 15-20 minutes preparation time
- you are examined for 15 minutes and receive the grade afterwards; you can present what you prepared and you should expect some follow up questions, i.e. the examination is not necessarily restricted to the questions you drew.

Exam questions usually have 2-4 subquestions. One subquestion is often about explaining concepts and results covered in the lecture. One subquestion is often an exercise similar to those done in class. Sometimes you are asked to link concepts. You do not have to know all the proofs we did by heart but you should know the main idea; in particular, you should be able to explain why a result holds.
You are responsible for the time management, i.e. for covering all subquestions within the 15 minutes. In the interest of time, it can be better to tell us immediately if you did not understand a subquestion. Sometimes we can then resolve the misunderstanding. 

* Organization
Lectures: Thursday 10:00-13:00 in 35-3-12 (apart from first lecture which is in 26.2.21)

If you have not taken Micro C (or forgotten most of it...), you should (re-)read chapters 1.1-1.3.A, 2.1 and 3.1, 3.2 in Robert Gibbons' Game Theory book before the course starts.

You are expected to *read the math handout* before the course and to *read the handout on notation* before the second lecture.

** Midterm
The midterm is a take home exam. You have to pass the midterm in order to be admitted to the final exam. The midterm should be done in groups of up to three people.  You have the weeks 41 and 42 (mid October) to work on the midterm. Deadline for handing in is October 23, 18:00.
The midterm exercises are here: [[https://github.com/KUGameTheory/gt2017/files/1366726/midterm.pdf][Midterm]]

A [[https://github.com/KUGameTheory/gt2017/files/1411366/midtermSolution.pdf][solution]] to the midterm is now available.

Here is a [[https://github.com/KUGameTheory/gt2017/files/1411376/Game.Theoryweb.pdf][list]] with students that are admitted to the final exam. Please, check whether you are on it and contact me if you are not (though you think you should).

** Final Exam
The final is an oral exam (with 20 minutes closed book preparation time). 

* Lecture Plan
** Uncertainty and risk
*** Lecture 1: Intro expected utility theorem 
- Introduction
- What is GT? 
- expected utility theorem
- reading:  MSZ 2.1-2.5 or MWG 6.A-6.B, (supplementary reading: Gilboa et al.  (2014))
# python: exercise lottery competition

 
** Solution concepts
*** Lecture 2: NE
- Fixed point theorems
- Nash existence theorem
- reading: MSZ 5.3, (supplementary reading: OR 2.4; a proof of Brouwer's fixed point theorem can be found in MSZ 23.1 but reading this proof is by no means necessary)
 # python: function that does the steps in the proof of Nash theorem (=fixed point solver?)
 
*** Lecture 3: Rationalizability and dominance
- Rationalizability and iterated elimination of dominated strategies
- reading: OR 4 or MSZ 4.5, 4.7, 4.11, 
 # python: iterative elimination of strictly dominated strategies in finite games and in Cournot (graphical)

*** Lecture 4: Correlated equilibrium
- Correlated equilibrium
- reading: OR 3.3 or MSZ 8 
 # python: correlated equilibrium solver

*** Lecture 5: Risk preferences 
- risk preferences
- impact of risk attitudes on the equilibrium set
- reading: MWG 6.C or MSZ 2.7-2.8, Weinstein (2016)


*** Lecture 6: Supermodular games: when solution concepts coincide
- Amir (2005), (supplementary reading: Milgrom and Roberts (1990))
 # python:??

** Knowledge

*** Lecture 7: Knowledge I
- Hat game
- Aumann model
- reading: OR 5.1-5.2 (or MSZ 9.1)
 # python: check whether event F is common knowledge in state w

*** Lecture 8: Knowledge II
- No agree to disagree
- (Common) knowledge and solution concepts
- Electronic mail game
- reading: OR 5.3-5.5 (or MSZ 9.2)
# python: ? sth about email game proof or induction ?


*** Lecture 9: Global Games I
- stag hunt
- reading: Carlson and van Damme (p. 989-993)
 # python: iterative elimination of strictly dominated strategies in stag hunt

*** Lecture 10: Global Games II
- private and public signal
- reading: Morris and Shin (2001)

** Matching

*** Lecture 11:  Deferred acceptance algorithm
- reading: Gale and Shapley (1962)

*** Lecture 12: School Choice
- top trading cycles algorithm
- reading: Abdulkadiroglu and  Sönmez (2003)

*** Lecture 13: Assignment problems
- position auctions
- reading: Varian (2007), (supplementary: Shapley and Shubik (1971))

* Material

** Handouts
- [[https://schottmueller.github.io/gt/math_gt.pdf][Math]] for Game Theory
- [[https://schottmueller.github.io/gt/gt_notation.pdf][Notation]] and preliminaries

** Lecture slides
- L01: [[https://github.com/KUGameTheory/gt2017/files/1277741/lecture01_expected_utility.pdf][slides]], [[https://schottmueller.github.io/gt//L01_expectedU/lottery_comp.html][extra]]
# - L02: [[./L02_gamesNE/strategic_form_games.pdf ][slides]], [[./L02_gamesNE/Nash_eq_solver2.html][extra]]
- L02: [[https://schottmueller.github.io/gt/L03_NashThm/Nash_thm.pdf ][slides]], [[https://schottmueller.github.io/gt/L03_NashThm/Nash_Brouwer.html][extra]]
- L03: [[https://schottmueller.github.io/gt/L04_rationalizability/ratio.pdf][slides]], [[https://schottmueller.github.io/gt/L04_rationalizability/rationalizability.html][extra]]
- L04: [[https://schottmueller.github.io/gt/L05_correlated_eq/corr_eq.pdf][slides]], [[https://schottmueller.github.io/gt/L05_correlated_eq/correlated_eq_solver_.html][extra]]
- L05: [[https://github.com/KUGameTheory/gt2017/files/1343487/riskAttitudes.pdf][slides]], [[./RiskAttitudesExercise.ipynb][solution extra exercise]]
- L06: [[https://schottmueller.github.io/gt/L06_supermodular/supermodular.pdf][slides]], [[https://schottmueller.github.io/gt/L06_supermodular/iasus.html][extra]]
- L07/08: [[https://github.com/KUGameTheory/gt2017/files/1454545/knowledge.pdf][slides]], [[https://schottmueller.github.io/gt/L10_11_knowledge/knowledge.html][extra]], [[https://github.com/KUGameTheory/gt2017/files/1456702/commonKnowledge.pdf][Handout]] showing the equivalence of the two definitions of common knowledge
- L09: [[https://github.com/KUGameTheory/gt2017/files/1477812/global_games.pdf][slides]], [[https://schottmueller.github.io/gt/L12_global/global_iter.html][extra]]
- L10: [[https://github.com/KUGameTheory/gt2017/files/1475752/globalGamesPublicSignal.pdf][slides]], [[https://github.com/KUGameTheory/gt2017/files/1475748/normalSignals.pdf][handout]] on normal signals,  [[https://github.com/KUGameTheory/gt2017/blob/master/GlobalGames2.ipynb][extra]]
- L11: [[https://github.com/KUGameTheory/gt2017/files/1064705/stable_matching.pdf][slides]] [[https://github.com/schottmueller/gametheory/blob/master/matching.org][extra]]
- L12: [[https://github.com/KUGameTheory/gt2017/files/1064703/school_choice.pdf][slides]]

The "extra" material is for your pleasure and entertainment and not relevant for the exam. The code you find in there is written in Python (there are literally hundreds of Python guides on the web if you are interested, e.g. https://lectures.quantecon.org/py/).


* Bibliography
OR: Osborne and Rubinstein 1994; A course in game theory; MIT Press (available as free ebook on the author's [[http://books.osborne.economics.utoronto.ca/][website]])

MSZ: Maschler, Salon and Zamir 2013; Game theory; Cambridge University Press (KU library [[http://dx.doi.org.ep.fjernadgang.kb.dk/10.1017/CBO9780511794216][link]])

MWG: MasColell, Whinston and Green 1995; Microeconomic theory; Oxford University Press

FT: Fudenberg and Tirole 1991; Game theory; MIT Press

Abdulkadiroglu, Atila, and Tayfun Sönmez. "School choice: A mechanism design approach." The American Economic Review 93.3 (2003): 729-747.

Amir, Rabah. "Supermodularity and complementarity in economics: an elementary survey", Southern Economic Journal, Vol. 71, No. 3 (2005): 636-660. [[https://www.jstor.org/stable/20062066][link]]

Aumann 1985: What is game theory trying to accomplish?; Frontiers of Economics; [[http://www.ma.huji.ac.il/~raumann/pdf/what%20is%20game%20theory.pdf][link]]

Carlson and van Damme "Global Games and Equilibrium Selection", Econometrica, Vol. 61, No. 5 (Sep., 1993), pp. 989-1018;  [[http://www.jstor.org.ep.fjernadgang.kb.dk/stable/2951491][link]]

Gale, David, and Lloyd S. Shapley. "College admissions and the stability of marriage." The American Mathematical Monthly 69.1 (1962): 9-15. [[http://www.jstor.org/stable/2312726][link]]

Gilboa, Itzhak, et al. "Economic models as analogies." The Economic Journal 124.578 (2014): pp.513-533. [[http://onlinelibrary.wiley.com/doi/10.1111/ecoj.12128/full][link]]

Jann, Ole, and Christoph Schottmüller. "Correlated equilibria in homogeneous good Bertrand competition." Journal of Mathematical Economics 57 (2015): 31-37. [[http://dx.doi.org/10.1016/j.jmateco.2015.01.005][link]]

Milgrom and Roberts “Rationalizability, Learning, and Equilibrium in Games with Strategic Complementarities”, Econometrica, Vol. 58, No. 6. (Nov., 1990), pp. 1255-1277; [[http://www.jstor.org.ep.fjernadgang.kb.dk/stable/2938316][link]]

Morris and Shin "Global Games: Theory and Applications", Econometric Society Monographs 35, 2003, 56-114 - Cambridge University Press; [[https://www.princeton.edu/~smorris/pdfs/paper_36_Global_Games.pdf][link]]

Morris, Stephen, and Hyun Song Shin. "Unique equilibrium in a model of self-fulfilling currency attacks." American Economic Review, Vol. 88, No. 3 (1998): 587-597. [[http://www.jstor.org/stable/116850 ][link]]

Morris, S. and H. S. Shin (2001). Rethinking multiple equilibria in macroeconomicmodeling. In NBER Macroeconomics Annual 2000, Volume 15, pp. 139–182. MIT Press. [[https://www.nber.org/chapters/c11056][link]]

Shapley, L. S. and M. Shubik (1971). The assignment game i: The core. International Journal of Game Theory 1 (1), 111–130.

Varian, Hal R. "Position auctions." International Journal of industrial Organization 25.6 (2007): 1163-1178. [[https://doi.org/10.1016/j.ijindorg.2006.10.002][link]]

Weinstein, Jonathan. "The Effect of Changes in Risk Attitude on Strategic Behavior." Econometrica 84.5 (2016): 1881-1902. [[http://onlinelibrary.wiley.com/doi/10.3982/ECTA13948/full][link]]
